### ISSUE TITLE
温馨提醒

### ISSUE THREAD

**Issue by KusStar** [UniversessH/Hackweek2020-Front-End#1]
https://github.com/UniversessH/Hackweek2020-Front-End/blob/ccb2b557a8f466d6221781a5850f913fdd2fc4a0/project/src/views/login/index.vue#L177-L181
为什么这样写？不是直接用 `loading` 就好了？

https://github.com/UniversessH/Hackweek2020-Front-End/blob/ccb2b557a8f466d6221781a5850f913fdd2fc4a0/project/src/views/login/index.vue#L137
为什么这样写？还有每次用 axios 都这样写了一次

**Comment by FuzzyFade** [comment]
为什么外面会多一个 project 文件夹无意义的去包一层 @UniversessH

**Comment by FuzzyFade** [comment]
路由没有鉴权
https://github.com/UniversessH/Hackweek2020-Front-End/blob/ccb2b557a8f466d6221781a5850f913fdd2fc4a0/project/src/router/index.js#L94-L96
